### ISSUE TITLE
Homeassistant Config

### ISSUE THREAD

**Issue by kashalls** [afreels95/HomeEnergyUsage#1]
Hey there,

Found you through your dashboard you uploaded to grafana labs.
Your home assistant configuration confuses me, how do you get the custom entities with homeassistant_..._kwh? Do you have a homeassistant config you can share?

Much appreciated!

**Comment by robtheone** [comment]
I can't speak for the author, but can tell you that it is going to take some work from your side to get this setup correctly for your sensor names and your specific situation, and there are LOTS of pieces of the puzzle to get everything up and running.  It has been a year since this was written, and Home Assistant has made several changes since then as well, so it won't "just work" using the included config files.  Did you read the article from which this configuration came? [Learn how to monitor your energy use at home with a Raspberry Pi, Grafana and Prometheus](https://grafana.com/blog/2021/04/15/learn-how-to-monitor-your-energy-use-at-home-with-a-raspberry-pi-grafana-and-prometheus/)   
This is VERY specific to using the Emporia Vue hardware to get sensor information into Home Assistant.  Are you using Emporia Vue sensors? If so, you will notice in the quoted article that he has a link to an HA Addon that creates the sensor names from the Emporia Vue App that is free to use along with the hardware: [HA-Emporia-Vue Addon](https://github.com/magico13/ha-emporia-vue).  I am using the the native Home Assistant addons for Grafana and Prometheus, and then added the Magico 13 HA-Emporia-Vue addon.  The sensor names will be the ones you labeled using the Emporia Energy app, then the Magico13 addon will import those sensors into HA and update them every minute.  You can change the sensor names (if needed) inside integrations of HA.  The ONLY change in my HA configuration.yaml was to add 

`prometheus:`
`  namespace: "" `  (there should be two spaces before this line, but can't make it add them here)

 (this namespace is optional to remove the HA prefix that was automatically added that I didn't like.) 

Home Assistant made changes to the sensor names AFTER this article and github was created, so it was a "breaking change" when 2021.8.0 Home Assistant Core was released and ALL my dashboards in grafana stopped working.  It took some time to figure out that HA added a default homeassistant_ prefix to all the metric names, as well as all sensor metrics now have a sensor_ name prefix.  If you read the "breaking changes" section of the 2021.8.0 HA Core, it tells you how to specifically relabel those sensors back to the way it was before OR another option would be to just update the grafana sensor names in each of the panels.  Here is the [breaking change notice:](https://www.home-assistant.io/blog/2021/08/04/release-20218/#breaking-changes) that include instructions on relabeling the sensor names should you decide to go this route.

Also, FYI, the sample grafana dashboard included here will have to be customized by you to match YOUR sensor names, as you will have your own sensors, very different from the ones included in the sample "home-energy-usage_rev1.json".  THIS is actually where all the changes are made  I opened the json file in notepad++, did a search for the sensors he had labeled, and updated them with my sensor names.  He also has his electric pricing listed there, and yours will likely be completely different.
Hope this helps!  Good luck

**Comment by kashalls** [comment]
I wasn't aware that there was an article behind this. I found it through Grafana labs and found this from searching GitHub. 

I am not using the Vue as I don't have access to our circuit breaker. I just couldn't tell if the "Total 1D" was made by combining sensors in the home assistant field or if it was by another addon.

Thanks for the information!
